/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.items;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@SpringBootApplication
//@ComponentScan(basePackages={"com.items.test"}) //basePackage를 지정한곳을 중심으로 @을 확인하여 실행
public class App {    
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
    
    @RequestMapping("/hello")
    String Hello() {
      return "Hello World!";
    }

	public Object getGreeting() {
		return "Hello World!";
	}

}
